project_name: determined-helm

build:
  skip: true

release:
  github:
    owner: asnelling
    name: determined
  mode: keep-existing
  extra_files:
    - glob: build/determined-*.tgz
      name_template: "determined-helm-chart_{{.Env.VERSION}}.tgz"
